### ISSUE TITLE
volcano.sh/vgpu-memory显示是0

### ISSUE THREAD

**Issue by bx0216** [Project-HAMi/volcano-vgpu-device-plugin#18]
我的环境是8块A100的gpu, 当使用volcano-vgpu-device-plugin-with-monitor.yml 或 volcano-vgpu-device-plugin.yml时
kubectl get node/gpu-node -o yaml显示的gpu显存为0，如下：
![微信图片_20240826151900](https://github.com/user-attachments/assets/62532a08-374f-4392-a7ea-1d5bb40805d4)

可以参考这个问题：
https://github.com/volcano-sh/devices/issues/19

**Comment by MiterV1** [comment]
同样的问题，不知道是否已解决

**Comment by Hugh-yw** [comment]
@bx0216 你好，请问你有么有测试过 卸载volcano-vgpu-device-plugin后，但是集群中节点信息中还存留 volcano.sh/vgpu-number、volcano.sh/gpu-memory 资源标签

**Comment by Hugh-yw** [comment]
> 是的，是卸载的问题。 标签没有更新。

还没解决是麽

**Comment by MiterV1** [comment]
解决了 需要使用最新的版本；
设置插件的gpu-memory-factor配置=10，在V100上可以正常识别

**Comment by yangjie727** [comment]
> 解决了 需要使用最新的版本； 设置插件的gpu-memory-factor配置=10，在V100上可以正常识别

请问这个需要用哪个最新的版本？

**Comment by yangjie727** [comment]
嗯，我昨天换了，已经正常了



---原始邮件---
发件人: ***@***.***&gt;
发送时间: 2024年11月19日(周二) 晚上10:42
收件人: ***@***.***&gt;;
抄送: ***@***.******@***.***&gt;;
主题: Re: [Project-HAMi/volcano-vgpu-device-plugin] volcano.sh/vgpu-memory显示是0 (Issue #18)




 
最新的构建版本，
 ***@***.***:fa3cf5a26a2a4f9dffae519183a51d97024b4d5dacbc02b5dc2b9e466e9d6788

**Comment by MiterV1** [comment]
请问你有遇到过cores无法隔离的问题吗，我现在发现cores无法隔离

**Comment by zj619** [comment]
> 最新的构建版本， volcano-vgpu-device-plugin:latest@sha256:fa3cf5a26a2a4f9dffae519183a51d97024b4d5dacbc02b5dc2b9e466e9d6788

这个镜像在哪下的
